name: Update
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: contents: write
    steps:
      - uses: actions/checkout@v3
      - run: python script.py
      - name: Debug and Push
        run: |
          ls -la  # זה יראה לנו בלוג אם data.json נוצר
          git config --global user.name 'bot'
          git config --global user.email 'bot@bot.com'
          git add data.json
          git commit -m "Update" || echo "Nothing to commit"
          git push
